#define _EOI_      0
#define ACTION     1
#define CODE_BLOCK 2
#define COLON      3
#define END_OPT    4
#define FIELD      5
#define LEFT       6
#define NAME       7
#define NONASSOC   8
#define OR         9
#define OTHER      10
#define PREC       11
#define RIGHT      12
#define SEMI       13
#define SEPARATOR  14
#define START      15
#define START_OPT  16
#define SYNCH      17
#define TERM_SPEC  18
#define TYPE       19
#define PERCENT_UNION 20
#define WHITESPACE 21
