/*@A (C) 1992 Allen I. Holub                                                */
#ifndef __CUR_H
#define __CUR_H

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <curses.h>	   /* routines in the library.		*/
#include <stdarg.h>	   /* va_list and va_start (ANSI)	*/
#include <tools/debug.h>
#include <tools/termlib.h>
#include <tools/box.h>     /* of IBM box-drawing characters	 	*/
#include "proto.h"	   /* function prototypes for curses functions  */
			   /* (distributed on disk but not printed here */

#endif /* __CUR_H */
